'use strict';
const themes=[
 {id:'carbohidratos',name:'Carbohidratos',title:'Cuidado con la lava',icon:'♨',color:'#bd3c24',pale:'#fff0e7',steps:'Cruza la ruta',motif:'●'},
 {id:'lipidos',name:'Lípidos',title:'Ruta de la membrana',icon:'◉',color:'#087f80',pale:'#e6f6f5',steps:'Explora la membrana',motif:'◉'},
 {id:'proteinas',name:'Proteínas',title:'Pliega la proteína',icon:'〰',color:'#7645b8',pale:'#f1eafa',steps:'Recorre la cadena',motif:'◆'},
 {id:'nucleotidos',name:'Nucleótidos',title:'Arma el nucleótido',icon:'⬡',color:'#2264ac',pale:'#e9f2ff',steps:'Reúne las piezas',motif:'⬡'},
 {id:'acidos-nucleicos',name:'Ácidos nucleicos',title:'Reconstruye la doble hélice',icon:'≋',color:'#ad3570',pale:'#fcebf3',steps:'Completa el recorrido',motif:'≋'},
 {id:'vitaminas',name:'Vitaminas',title:'Laboratorio de vitaminas',icon:'✦',color:'#796000',pale:'#fff7d3',steps:'Visita las estaciones',motif:'▣'}
];
const root=document.querySelector('#app');
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
let game,theme;
function button(text,cls,fn){const b=el('button',cls,text);b.type='button';b.onclick=fn;return b;}
function menu(message){document.title='BioMisterio · Desafíos de bioquímica';root.replaceChildren();root.removeAttribute('style');if(message)root.append(el('p','notice',message));const intro=el('section','intro');intro.append(el('p','eyebrow','SEIS TEMAS · UN NUEVO RETO'),el('h1','', 'La ciencia guarda misterios.\nResuelve el siguiente.'),el('p','lead','Elige una expedición. Responde 10 preguntas y descubre la explicación después de cada respuesta.'));root.append(intro);const grid=el('div','theme-grid');themes.forEach((t,i)=>{const a=el('a','theme-card');a.href='?tema='+t.id;a.style.setProperty('--accent',t.color);a.style.setProperty('--pale',t.pale);const top=el('div','card-top');top.append(el('span','theme-icon',t.icon),el('span','eyebrow','0'+(i+1)));a.append(top,el('h2','',t.name),el('p','',t.title));const bottom=el('div','card-bottom');bottom.append(el('span','','10 preguntas · 100 puntos'),el('span','enter','Entrar ↗'));a.append(bottom);grid.append(a);});root.append(grid);}
function render(focus=false){root.replaceChildren();root.style.setProperty('--accent',theme.color);root.style.setProperty('--pale',theme.pale);document.title=theme.name+' · BioMisterio';const nav=el('div','game-nav');const back=el('a','back','← Elegir otro tema');back.href='?';nav.append(back,el('span','eyebrow',theme.name));root.append(nav);const heading=el('div','game-heading');heading.append(el('span','theme-icon',theme.icon),el('h1','',theme.title));root.append(heading);
 const stats=el('div','stats');stats.append(el('span','',game.finished?'Desafío completado':`Pregunta ${game.index+1} de 10`),el('strong','score',`${game.score} / 100 puntos`));root.append(stats);const progress=el('progress');progress.max=10;progress.value=game.answers.length;progress.setAttribute('aria-label','Preguntas respondidas');root.append(progress);
 const path=el('div','journey');path.setAttribute('aria-hidden','true');for(let i=0;i<10;i++){const step=el('span','step'+(i<game.answers.length?' done':''),theme.motif);path.append(step);}root.append(path);
 if(game.finished){const panel=el('section','question-panel result');panel.append(el('p','eyebrow','EXPEDICIÓN COMPLETADA'),el('h2','',`${game.score} puntos`),el('p','lead',`${game.score/10} aciertos de 10 preguntas.`),el('p','', 'Cada explicación es una nueva pista. Puedes volver a intentarlo cuando quieras.'),button('Repetir desafío','primary',()=>{game.reset();render(true);}));const other=el('a','back','Elegir otro tema');other.href='?';panel.append(other);root.append(panel);if(focus){panel.tabIndex=-1;panel.focus();}return;}
 const q=game.current,panel=el('section','question-panel');panel.append(el('p','eyebrow',q.tag));const h=el('h2','question',q.question);h.tabIndex=-1;panel.append(h);const choices=el('div','choices');q.options.forEach(o=>{const b=button('','option',()=>{if(game.answer(o.key))render();});const answered=game.selected!==null;b.disabled=answered;b.append(el('span','option-key',o.key),el('span','option-text',o.text));if(answered&&o.key===q.correct){b.classList.add('correct');b.append(el('span','answer-symbol','✓'));b.setAttribute('aria-label',o.key+'. '+o.text+'. Respuesta correcta');}else if(answered&&o.key===game.selected){b.classList.add('incorrect');b.append(el('span','answer-symbol','✕'));}choices.append(b);});panel.append(choices);
 const feedback=el('div','feedback');feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');if(game.selected!==null){const right=game.selected===q.correct;feedback.classList.add(right?'right':'wrong');feedback.append(el('strong','',right?'✓ ¡Correcto! +10 puntos':'✕ Esta vez no. +0 puntos'),el('p','',q.feedback));}panel.append(feedback);const next=button(game.index===9?'Ver resultado':'Siguiente →','primary',()=>{if(game.next())render(true);});next.disabled=game.selected===null;panel.append(next);root.append(panel);if(focus)h.focus();}
try{BioGame.validate(window.BIO_QUESTIONS,themes.map(t=>t.id));const id=new URLSearchParams(location.search).get('tema');theme=themes.find(t=>t.id===id);if(theme){game=new BioGame(BIO_QUESTIONS.filter(q=>q.theme===id));render();}else menu(id?'Ese tema no existe. Elige uno de los seis desafíos.':null);}catch(error){root.replaceChildren(el('h1','','No se puede iniciar el desafío'),el('p','','El banco de preguntas no pasó la validación. Revisa questions.js antes de publicar.'));console.error(error);}
